# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_services',
            old_name='impage_path',
            new_name='image',
        ),
    ]
