# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntuser_systeminternalstools',
            name='key_name',
            field=models.CharField(max_length=300),
        ),
    ]
