# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0003_auto_20170514_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_sysinfo',
            name='time_zone',
            field=models.CharField(default=2013, max_length=200),
            preserve_default=False,
        ),
    ]
