# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0004_system_sysinfo_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_sysinfo',
            name='computer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
