# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0005_system_sysinfo_computer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_sysinfo',
            name='time_zone',
            field=models.CharField(default=2014, max_length=200),
            preserve_default=False,
        ),
    ]
