# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0006_software_sysinfo_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_sysinfo',
            name='computer_name',
            field=models.CharField(default=2015, max_length=200),
            preserve_default=False,
        ),
    ]
