# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0007_software_sysinfo_computer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software_sysinfo',
            name='last_write',
        ),
    ]
