# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registryApp', '0008_remove_software_sysinfo_last_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_sysinfo',
            name='installed_date',
            field=models.CharField(max_length=200),
        ),
    ]
